# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-02 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('U_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u7528\u6237id')),
                ('U_phone', models.CharField(max_length=11, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('U_name', models.CharField(max_length=50, verbose_name='\u540d\u5b57')),
                ('U_pwd', models.CharField(max_length=50, verbose_name='\u5bc6\u7801')),
                ('M_sex', models.CharField(max_length=20, verbose_name='\u6027\u522b')),
                ('U_addr', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
                ('U_school', models.CharField(max_length=100, verbose_name='\u5b66\u6821')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u4fe1\u606f',
                'verbose_name_plural': '\u7528\u6237\u4fe1\u606f',
            },
        ),
    ]
